### ISSUE TITLE
Error in hclust(d = d.dist, method = "average") : NA/NaN/Inf in foreign function call (arg 10)

### ISSUE THREAD

**Issue by amydy** [lmc297/bactaxR#5]
I have the same problem of this R script.

> summary(ani)
An object of class bactaxRObject 
Number of genomes:  33 
Total number of pairwise ANI comparisons:  1086> h <- ANI.histogram(bactaxRObject = ani, bindwidth = 0.1)
> h
> dend <- ANI.dendrogram(bactaxRObject = ani, ANI_threshold = 95, xline = c(4,5,6,7.5), xlinecol = c("#ffc425", "#f37735", "deeppink4", "black"), label_size = 0.5)

I did this one exactly but I get the error message.(Error in hclust(d = d.dist, method = "average") : NA/NaN/Inf in foreign function call (arg 10))
Also, I check the file and I can't find the NA/NaN/Inf 
I don't understand what the NA/NaN/Inf mean,

Can you solve this problem, please.

**Comment by lmc297** [comment]
Hi amydy,
According to this, you have 33 genomes in your data set; you need pairwise similarities calculated between all genomes, which in your case, should be 33*33 = 1089. There appear to only be 1086 pairwise comparisons in your file/data frame.

**Comment by amydy** [comment]
Hi Imc297

I'll make input file 33*33=1089. Then I'll try again

Thank you
