### ISSUE TITLE
What do the lengths of the edges in the weighted undirected graphs mean?

### ISSUE THREAD

**Issue by kehletdelgado** [lmc297/bactaxR#6]
Does it represent the ANI of that pair? 
Or does edge weight represent the ANI?

Thank you!

**Comment by lmc297** [comment]
Hello! I'm assuming you're referring to the edges in the graph produced by `ANI.graph`? If so, the edges simply connect two nodes (genomes) that share an ANI value above your threshold of choice; you can set this using `ANI_threshold` (by default, `ANI_threshold = 95`, so two genomes with >= 95 ANI will be connected by an edge, and two genomes < 95 ANI will not be connected by an edge).

**Comment by kehletdelgado** [comment]
[wgs_fix_95_composite.pdf](https://github.com/lmc297/bactaxR/files/13311763/wgs_fix_95_composite.pdf)

Thank you for the reply! I have found your R package very useful. Is there any meaning to the lengths of the edges (Why are some longer (and nodes further apart) than others in the attached graph)?

**Comment by lmc297** [comment]
I'm so glad to hear that you're finding the package useful! The edge lengths don't really have any biological meaning; it's just a way to visualize pairwise ANI values in two dimensions in a way that looks "nice" (i.e., using the graphopt layout algorithm: https://igraph.org/r/doc/layout_with_graphopt.html).

**Comment by kehletdelgado** [comment]
That makes sense. Thank you for the information!
